version: '3'

services:
  
  database:
    image: bitnami/postgresql:15
    container_name: exam-db
    env_file:
      - .properties
    ports:
      - "5434:5432"
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
      - ./db-init:/docker-entrypoint-initdb.d

volumes:
  pgdbdata: